name: Reveal solution after lecture
on:
  workflow_dispatch:

jobs:
  reveal-solution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cp -r .instructor/solution ./solution
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add solution
          git commit -m "Add solution after lecture" || echo "No changes"
          git push
